---
- hosts: thunderbird_data
  remote_user: ubuntu
  
  tasks:
    - name: Provision base requirements
      import_role:
        name: base

    - name: Setup data node
      import_role:
        name: elasticsearch
      vars:
        node:
          name: "data"
          port: 9201
          hosts: "{{ hostvars['localhost'].ec2 | json_query('instances[*].private_ip_address') }}"